
parameters:
    uploads_dir: '%kernel.project_dir%/public/uploads'

services:
    App\Service\ImageUploaderService:
        arguments:
            $projectDir: '%kernel.project_dir%' 
            $filesystem: '@Symfony\Component\Filesystem\Filesystem'  

    _defaults:
        autowire: true     
        autoconfigure: true 
        bind:
            string $projectDir: '%kernel.project_dir%'  
            string $uploadsDir: '%uploads_dir%' 

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Symfony\Component\Filesystem\Filesystem: ~
